language: node_js
node_js:
- '6.1'
install:
- npm install
- bower install
script:
- ./deploy.sh
env:
  global:
  - GITHUB_REPO: open-curriculum/seed
  - secure: j0fddFDJ5Ifs1i12bhqCOs2EYlSGnbBhA6PHycEICJ8mARu0RSLMkdI8u64+1ergMzIF0icG8w5dTnk2uIWX9FF3ZMQUGE0ApAWLcPKoM/u/ECg/hl7V+ej54PjZhkMi4USTCOMDC11sfQUyVtazyhjc90id03IAgU1fXot1poWuccnu56AFqMjDWrqS6iDqLIugoqO4hPKk5hrU6gu6q97vu0YJRSlVdSrg9NIMMLq0Jbk85PHg2yTm9s6qoBEuukbXkHCs8cyFk2avsRPw+aO6zSOFZ0FZemtjdu6do6EgptoaT/vYANzYmW5Fl1IvGPkKApcV5CPJqC/fGt+W2hppMV6Cy3wVFmFwV8OrJ7oZ5Csl3KyqA2k2pXVMOxUnoZLp2VSuqTp1JnTObuumVMyoPBJPKO8yByzkKTRT7kJY8cVOxPMgC1vnurp/bdLCKnycMs7HinrcMCeVddIICYDwSBzRYSVA5oyKHdtINXDzC/G3+LM3dcSoQs4m8XPaLRcWN/2+pnUgLk9X6UwoUcTueEmvWbpgnscZ1GB7EQlUG4ILs0MOl0hwrruAL6EfT9BntsMH1EmKL2tLofLksPb4SOWpN+gO/zoibXyjqtj+eq/j3g8wXGz4dkXFUIXsmV6E+mL3Epn1XQP58XDXXcPZR9y3D6FsmvhXS4LQeTI=
branches:
  only:
  - master
